apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nodeapp
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
        - name: imagestore
          image: ghcr.io/mayntri/hello-world-rest-api
          ports:
            - containerPort: 3000
